config/routes.rb
Rails.application.routes.draw do

  resources :soudan, only: [:index, :kiyaku, :privacy_policy]
  root 'soudan#index'

  devise_for :users, controllers: {
  omniauth_callbacks: 'users/omniauth_callbacks',
  confirmations: 'users/confirmations',
  passwords:     'users/passwords',
  registrations: 'users/registrations',
  sessions:      'users/sessions',
  }

  devise_scope :user do
    get '/users/sign_out' => 'users/sessions#destroy'
  end

  resources :users do
    resources :bads, only: [:create, :destroy]
    resources :user_chat_rooms, only: [:index], as: 'chat_rooms'
    resources :messages, only: [:create, :destroy]
    resources :messages do
      resources :thanks, only: [:create, :destroy]
      resources :bads, only: [:create, :destroy]
    end
  end

  resources :users, path: '/', only: [:user_topics]


  resources :topics do
    resource :closes, only: [:create]
    resources :chat_rooms
  end

  get 'test', to: 'soudan#test', as: 'test'
  get 'user/index', to: 'users#index', as: 'user_index'
  get 'users/:id/topics', to: 'users#user_topics', as: 'user_topics'
  get 'search', to: 'topics#search', as: 'topics_search'
  get 'category', to: 'topics#category', as: 'category_search'
  get 'kiyaku', to: 'soudan#kiyaku', as: 'kiyaku'
  get 'privacy_policy', to: 'soudan#privacy_policy', as: 'privacy_policy'
  get 'contact', to: 'soudan#contact', as: 'contact'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/bad.rb
class Bad < ApplicationRecord

  belongs_to :message
  belongs_to :user
end

app/controllers/bads_controller.rb
class BadsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_variables

  def create
    Bad.create(user_id: params[:user_id], message_id: params[:message_id])
    render 'bad_ajax.js.erb'
  end

  def destroy
    bad = Bad.find(params[:id])
    bad.destroy
    render 'bad_ajax.js.erb'
  end

  private
  def set_variables
    @message = Message.find(params[:message_id])
    @id_name = "#bad-btn-#{@message.id}"
  end

end

app/views/bads/_bad.haml
.bad-ajax{:id => "bad-btn-#{message.id}"}
  - if message.bad.blank? && message.user_id != current_user.id && message.chat_room.topic_create_user_id != message.user_id
    .bad-btn
      = link_to '不適切な返信', user_message_bads_path(user_id: message.user_id, message_id: message.id), method: :post, data: { confirm: '本当によろしいですか?' }, remote: true
  - elsif message.bad.present? && message.user_id != current_user.id && message.chat_room.topic_create_user_id != message.user_id
    .bad-btn-aledy
      = link_to '&#10003; 不適切な返信'.html_safe, user_message_bad_path(user_id: message.user_id, message_id: message.id, id: message.bad.id), method: :delete, data: { confirm: '不適切な返信を解除します' }, remote: true

app/views/bads/bad_ajax.js.erb
$("<%= @id_name %>").html("<%= escape_javascript(render partial: 'bads/bad', locals: {message: @message}) %>");

app/views/bads/create.js.erb
<%# ERBタグを用いることでコントローラにて定義した@receiving_userの値を取得できます %>
<%# また同様にERBタグを用いて部分テンプレートも適用できます(jを用いてエスケープ処理を行う必要あり) %>
$("#like-button-zone_<%= @receiving_user.id %>").html("<%= j(render partial: 'likes/like', locals: { user: @receiving_user }) %>");
<%# いいね残高をコントローラにて定義した@sending_userを用いて表示します %>
$(".like_balance").html("<%= @sending_user.like_balance %>")