config/routes.rb
Rails.application.routes.draw do

  resources :soudan, only: [:index, :kiyaku, :privacy_policy]
  root 'soudan#index'

  devise_for :users, controllers: {
  omniauth_callbacks: 'users/omniauth_callbacks',
  confirmations: 'users/confirmations',
  passwords:     'users/passwords',
  registrations: 'users/registrations',
  sessions:      'users/sessions',
  }

  devise_scope :user do
    get '/users/sign_out' => 'users/sessions#destroy'
  end

  resources :users do
    resources :bads, only: [:create, :destroy]
    resources :user_chat_rooms, only: [:index], as: 'chat_rooms'
    resources :messages, only: [:create, :destroy]
    resources :messages do
      resources :thanks, only: [:create, :destroy]
      resources :bads, only: [:create, :destroy]
    end
  end

  resources :users, path: '/', only: [:user_topics]


  resources :topics do
    resource :closes, only: [:create]
    resources :chat_rooms
  end

  get 'test', to: 'soudan#test', as: 'test'
  get 'user/index', to: 'users#index', as: 'user_index'
  get 'users/:id/topics', to: 'users#user_topics', as: 'user_topics'
  get 'search', to: 'topics#search', as: 'topics_search'
  get 'category', to: 'topics#category', as: 'category_search'
  get 'kiyaku', to: 'soudan#kiyaku', as: 'kiyaku'
  get 'privacy_policy', to: 'soudan#privacy_policy', as: 'privacy_policy'
  get 'contact', to: 'soudan#contact', as: 'contact'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/topic.rb
class Topic < ApplicationRecord
  include IdGenerator

  belongs_to :category
  belongs_to :user
  has_many :chat_rooms, dependent: :destroy
  has_one :close

  validates :title, presence: true
  validates :text, presence: true
  validates :category_id, presence: true


end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!, only: [:show, :new, :create, :edit, :update, :destroy]
  before_action :set_user, only: [:index, :new, :create, :show, :edit, :update, :destroy, :search, :category]
  before_action :set_form_data, only: [:new, :edit, :search, :category]

  def index
    @topic = Topic.all.order(updated_at: "DESC")
  end


  def show
    @topic = Topic.find(params[:id])
    @chat_room=ChatRoom.where(topic_id: @topic.id)
    @chat_room.each do |chat_room|
      if chat_room.topic_create_user_id.present?  && chat_room.sender_user_id == current_user.id   #ログインユーザーとtopic所有者のチャットルームがあるか確認
        @check_room = true  #すでにチャットルームがあるので、後のビュー画面切り替えのために@check_roomにtrueの文字を入れておく
        @room_id = chat_room.id  #ハッシュに入っているチャットルームidを取り出しビューに渡す（リンクアドレスに入れるため）
      end
    end
    if @check_room.present?         #値が入っていれば
    else    #値が入っていなければ（チャットルームがなければ）新しいチャットルームを作るためのインスタンスを作る。
      @chat_room = ChatRoom.new
      @user_chat_room = UserChatRoom.new
    end
  end


  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    if @topic.save
      redirect_to topics_path
      flash[:success] = "投稿が完了しました"
    else
      redirect_back(fallback_location: root_path)
      flash[:alert] = "必須項目をすべて選択してください"
    end
  end

  def search
  end

  def category
    @topics = Topic.where(category_id: params[:id]).limit(50).order(updated_at: "DESC")
  end

  protected
  def set_form_data
    @category = Category.all
  end

  def set_user
    @user = User.find(current_user.id) if user_signed_in?
  end


  private
  def topic_params
    params.require(:topic).permit(:title, :category_id, :text).merge(user_id: current_user.id)
  end

end

app/views/topics/_category-img.haml
.category-wrap__img
  = link_to category_search_path(id:category.id) do
    = image_tag category.image
    .category-wrap__img__text
      = category.name

app/views/topics/_topic-box.haml
.topic-box
  = link_to topic_path(topic.id) do
    .topic-box__inner
      .topic-box__inner__left
        - if topic.close.blank?
          .status-now 受付中
        - else
          .status-close 解決済み
        .status-mail 返信
        .status-mail-count
          #{topic.chat_rooms.count}
      .topic-box__inner__right
        .topic-box__inner__right__title
          #{topic.title}
        .topic-box__inner__right__info
          .topic-box__inner__right__info__category
            #{topic.category.name}
          .topic-box__inner__right__info__messanger
            .topic-box__inner__right__info__messanger__user
              - if topic.user.nil?
                退会済みユーザー
              - else
                #{topic.user.name}
            .topic-box__inner__right__info__messanger__time
              = time_ago_in_words(topic.created_at)+"前"

app/views/topics/category.haml
.mobile-body
  =render 'shared/header'
  .mobile-body__inner
    -# .search-frame
    -#   = form_with url: topics_search_path, method: :get, local: true do |f|
    -#     .search-frame__flex
    -#       = f.label "カテゴリー"
    -#       .search-frame__category.search-category
    -#         = f.collection_select :category_id, @category, :id, :name, {prompt: "選択してください"}
    -#       = f.submit '決定', class:"post-btn", id:"search-category-btn"
    %section#search-frame__body
      #search-frame__inner
        - if @topics.blank?
          %p 投稿はありません
        - else
          =render partial: 'topic-box', collection: @topics, as: :topic
    - if user_signed_in?
      -# =render 'shared/footer'

app/views/topics/index.haml
.mobile-body
  =render 'shared/header'
  .mobile-body-fixe-flame
    .mobile-body__inner
      =render partial: 'topic-box', collection: @topic, as: :topic
  - if user_signed_in?
    -# =render 'shared/footer'

app/views/topics/new.haml
.mobile-body
  =render 'shared/header'
  .mobile-body-fixe-flame
    .mobile-body__inner
      = form_for @topic do |f|
        .topic-new-box
          .topic-new-box__inner
            = f.label "タイトル"
            %br/
            = f.text_area :title, autofocus: true, autocomplete: "off", class:"topic-input", placeholder: "タイトルを入力してください"
            %br/
          .topic-new-box__inner
            = f.label "カテゴリー"
            %br/
            = f.collection_select :category_id, @category, :id, :name, {prompt: "選択してください"}, class:"topic-category-input"
          .topic-new-box__inner
            = f.label "内容"
            %br/
            = f.text_area :text, autofocus: true, autocomplete: "off", class: "topic_text"
          .topic-new-box__inner#topic-new__post-btn-flame
            .post-btn
              = f.submit :投稿
  -# =render 'shared/footer'

app/views/topics/search.haml
.mobile-body
  =render 'shared/header'
  .mobile-body__inner
    .category-wrap
      =render partial: 'category-img', collection: @category, as: :category

app/views/topics/show.haml
.mobile-body
  =render 'shared/header'
  .topic-show-box
    .topic-show-box__inner
      .topic-show-box__inner__top
        .topic-show-box__flex-box
          .topic-show-box__inner__user-icon
            - if @topic.user.present?
              = image_tag @topic.user.image
          .topic-show-box__inner__user-name
            - if @topic.user.present?
              #{@topic.user.name}
            - else
              退会済みユーザー
        .topic-show-box__inner__title
          #{@topic.title}
      .topic-show-box__inner__bottom
        .space-1
        .topic-show-box__flex-box.border-bottom
          .icon-text 相談内容
          .topic-show-box__inner__category-name
            #{@topic.category.name}
          .topic-show-box__inner__time
            = time_ago_in_words(@topic.created_at)+"前"
        .topic-show-box__inner__text
          = simple_format @topic.text
        .space-3
        - if @topic.user_id != current_user.id
          - if @check_room == true
            %a.post-btn{href: topic_chat_room_path(topic_id: @topic.id, id: @room_id)} メッセージルームへ
          - else
            = form_with url:topic_chat_rooms_path(topic_id: @topic.id), local: true do |f|
              = fields_for @user_chat_room do |e|
                = e.hidden_field :topic_create_user_id, value: @topic.user_id
                = f.submit "相談相手になる", class:"post-btn"
  -# =render 'shared/footer'