config/routes.rb
Rails.application.routes.draw do

  resources :soudan, only: [:index, :kiyaku, :privacy_policy]
  root 'soudan#index'

  devise_for :users, controllers: {
  omniauth_callbacks: 'users/omniauth_callbacks',
  confirmations: 'users/confirmations',
  passwords:     'users/passwords',
  registrations: 'users/registrations',
  sessions:      'users/sessions',
  }

  devise_scope :user do
    get '/users/sign_out' => 'users/sessions#destroy'
  end

  resources :users do
    resources :bads, only: [:create, :destroy]
    resources :user_chat_rooms, only: [:index], as: 'chat_rooms'
    resources :messages, only: [:create, :destroy]
    resources :messages do
      resources :thanks, only: [:create, :destroy]
      resources :bads, only: [:create, :destroy]
    end
  end

  resources :users, path: '/', only: [:user_topics]


  resources :topics do
    resource :closes, only: [:create]
    resources :chat_rooms
  end

  get 'test', to: 'soudan#test', as: 'test'
  get 'user/index', to: 'users#index', as: 'user_index'
  get 'users/:id/topics', to: 'users#user_topics', as: 'user_topics'
  get 'search', to: 'topics#search', as: 'topics_search'
  get 'category', to: 'topics#category', as: 'category_search'
  get 'kiyaku', to: 'soudan#kiyaku', as: 'kiyaku'
  get 'privacy_policy', to: 'soudan#privacy_policy', as: 'privacy_policy'
  get 'contact', to: 'soudan#contact', as: 'contact'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/user.rb
class User < ApplicationRecord
  include IdGenerator

  mount_uploader :image, ImageUploader

  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :omniauthable,
         omniauth_providers: %i[line google_oauth2]

  has_many :messages
  has_many :topics
  has_many :chat_rooms, through: :user_chat_room
  has_many :user_chat_rooms
  has_many :thanks, dependent: :destroy
  has_many :bads, dependent: :destroy

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def line
    @auth = request.env['omniauth.auth']
    # ユーザーはすでにサービスに登録しているか複合検索
    @user = User.where(provider: @auth[:provider], uid: @auth[:uid]).first
    if @user
      # 既にサービスに登録していればログイン処理
      bypass_sign_in(@user)
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'LINE'
      redirect_to topics_path and return
    else
      # サービスに登録していなければSNS情報を基に新規に登録
      # LINEユーザーはmailアドレス持っておらずnull制約で登録できなくなるのでフェイクアドレスを作る
      email = @auth[:info][:email] ? @auth[:info][:email] : "#{@auth[:uid]}-#{@auth[:provider]}@example.com"
      # 下記のよりcreateメソッド
      @user = current_user || User.create!(
        provider: @auth[:provider],
        uid:      @auth[:uid],
        remote_image_url: @auth[:info][:image],
        name:     @auth[:info][:name],
        email:     email,
        password: Devise.friendly_token[0, 20],
      )
      if @user.persisted?
        # 新たにレコードが作られたか
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'LINE'
        bypass_sign_in(@user)
        # ログインさせマイページに遷移
        redirect_to user_path(@user.id) and return
      else
        # 失敗の際はアカウン登録画面に遷移
        session['devise.line_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow   some session stores
        redirect_to new_user_registration_path, alert: @user.errors.full_messages
      end
    end
  end

  def google_oauth2
    # authサーバーからSNS情報を取得
    @auth = request.env['omniauth.auth']
    # authサーバーから取得したメールアドレスがUserテーブルにあるかチェック
    if User.find_by(email: @auth[:info][:email]).blank?
      # アカウントない場合にcreate
      @user = User.create(
        name: @auth[:info][:name],
        email: @auth[:info][:email],
        provider: @auth[:provider],
        uid:      @auth[:uid],
        remote_image_url: @auth[:info][:image],
        password: Devise.friendly_token[0,20]
      )
      # @userが新規に作られたらログイン処理に移行
      if @user.persisted?
      bypass_sign_in(@user)
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      redirect_to user_path(@user.id) and return
      else
      # 登録に失敗した場合は情報を持たせたままアカウント登録に遷移
      session["devise.#{provider}_data"] = oauth.except("extra")
      redirect_to new_user_registration_path, alert: @user.errors.full_messages
      end
    else
      # authサーバーから取得したメールアドレスがUserテーブルにあった場合@userに持たせてログインメソッドへ
      @user = User.find_by(email: @auth[:info][:email])
      bypass_sign_in(@user)
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      redirect_to user_path(@user.id) and return
    end
  end

end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  def create
    super
    # UserMailer.send_message_to_user(@entry.user).deliver_now
  end
  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create, :new, :campany]
  before_action :configure_account_update_params, only: [:edit, :update]

  # POST /resource


  def create
    super
    user = User.new(configure_sign_up_params)
    user.save
  end


  def after_sign_up_path_for(resource)
    user_path(current_user.id)
  end

  def after_update_path_for(resource)
    user_path(current_user.id)
  end



  protected


  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up,keys: [:name, :image])
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :image])
  end



end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end


  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected
  def after_sign_out_path_for(resource)
    new_user_session_path
  end

  def after_sign_in_path_for(resource)
    topics_path
  end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :edit, :update, :destroy, :user_topics, :mypage]
  before_action :set_user, only: [:show, :update, :destroy, :user_topics, :mypage]

  def index
    @user = User.new
    @users = User.all
  end



  def show
        @user = User.find(params[:id])
  end

  def user_topics
    if Topic.where(user_id: current_user.id).present?
      @topic = Topic.where(user_id: current_user.id).order(updated_at: "DESC")
    else
      @no_topics = "投稿はありません"
    end
  end

  private
    def set_user
      if current_user.id == params[:id]
        @user = User.find(params[:id])
      else
        redirect_to new_user_session_path
      end
    end



end

app/views/users/_form.html.haml
= form_with(model: user, local: true) do |form|
  - if user.errors.any?
    #error_explanation
      %p
        = pluralize(user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - user.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :name
    = form.text_field :name, id: :user_name
  .field
    = form.label :image
    = form.text_field :image, id: :user_avater
  .field
    = form.label :category_id
    = form.number_field :category_id, id: :user_category_id
  .actions
    = form.submit

app/views/users/_user-topics.haml
.topic-box
  .topic-box__inner
    .topic-box__inner__left
      = link_to topic_chat_rooms_path(topic_id: topic.id) do
        - if topic.close.blank?
          .status-now 受付中
        - else
          .status-close 解決済み
        .status-mail#status-mail 返信
        .status-mail-count#status-mail-count
          #{topic.chat_rooms.count}件
    - case params.values_at :controller, :action
    - when ['users', 'user_topics']
      #topic-box__inner__right
        = link_to topic_path(topic.id) do
          .topic-box__inner__right__title
            トッピック名：#{topic.title}
          .topic-box__inner__right__info
            .topic-box__inner__right__info__category
              #{topic.category.name}
    - else
      .topic-box__inner__right
        = link_to topic_path(topic.id) do
          .topic-box__inner__right__title
            #{topic.title}
          .topic-box__inner__right__info
            .topic-box__inner__right__info__category
              #{topic.category.name}
    - case params.values_at :controller, :action
    - when ['users', 'user_topics']
      - if topic.close.blank?
        .topic-close
          = link_to '受付を終了する', href=topic_closes_path(topic_id: topic.id), method: :post, data: { confirm: '相談を終了します' }

app/views/users/index.haml
=render 'shared/header'
-# =render 'shared/top-page-header'
.my-page
  .my-card
    .my-card__user-avater
      .my-card__user-avater__inner
        = image_tag @user.image
    .my-card__user-name
      %strong #{@user.name}
    .my-card__status
      %p Record
      .star-rating-box
        .star-rating
          .star-rating-front{:style => "width: #{star_rate}"} ★★★★★
          .star-rating-back ★★★★★
        %p #{@user.thanks.count}
        %p #{@user.bads.count}
-# =render 'shared/footer'

app/views/users/mypage.html.haml
.my-page
  =render 'shared/header'
  .space-10
  .my-page-flame
    .my-card
      .my-card__user-avater
        .my-card__user-avater__inner
          = image_tag @user.image
      .my-card__name-and-status
        .my-card__user-name
          %p #{@user.name}
        .my-card__status
          良い評価　
          %p #{@user.thanks.count}
        .my-card__status
          悪い評価　
          %p #{@user.bads.count}

    .my-page-flame__innner
      %li.global-nav__item
        %a{href: topics_search_path}
          %i.material-icons.md-dark.md-inactive#material-icons-custom
            search
            %p カテゴリー検索

      %li.global-nav__item
        %a{href: topics_path}
          %i.material-icons.md-dark.md-inactive#material-icons-custom
            format_list_bulleted
            %p 投稿一覧

      %li.global-nav__item
        %a{href: user_chat_rooms_path(user_id: current_user.id)}
          %i.material-icons.md-dark.md-inactive#material-icons-custom
            message
            %p 受信メッセージ一覧

      %li.global-nav__item
        %a{href: user_topics_path(current_user.id)}
          %i.material-icons.md-dark.md-inactive#material-icons-custom
            list_alt
            %p あなたの投稿一覧

      %li.global-nav__item
        %a{href: edit_user_registration_path}
          %i.material-icons#material-icons-custom
            settings
            %p 各種設定

      %li.global-nav__item
        %a{href: destroy_user_session_path,  method: :delete}
          %i.material-icons#material-icons-custom
            exit_to_app
            %p ログアウト


=render 'shared/footer-bar'

app/views/users/new.html.haml
%h1 New User
= render 'form', user: @user
= link_to 'Back', users_path

app/views/users/show.haml
.my-page
  =render 'shared/header'
  .space-10
  .my-page-flame
    .my-card
      .my-card__user-avater
        .my-card__user-avater__inner
          = image_tag @user.image
      .my-card__name-and-status
        .my-card__user-name
          %p #{@user.name}
        .my-card__status
          良い評価　
          %p #{@user.thanks.count}
        .my-card__status
          悪い評価　
          %p #{@user.bads.count}

    .my-page-flame__innner
      %li.global-nav__item
        %a{href: topics_search_path}
          %i.material-icons.md-dark.md-inactive#material-icons-custom
            search
            %p カテゴリー検索

      %li.global-nav__item
        %a{href: topics_path}
          %i.material-icons.md-dark.md-inactive#material-icons-custom
            format_list_bulleted
            %p 投稿一覧

      %li.global-nav__item
        %a{href: user_chat_rooms_path(user_id: current_user.id)}
          %i.material-icons.md-dark.md-inactive#material-icons-custom
            message
            %p 送受信メッセージ一覧
        .new_message_badge.users-show
          %p= new_message_badge

      %li.global-nav__item
        %a{href: user_topics_path(current_user.id)}
          %i.material-icons.md-dark.md-inactive#material-icons-custom
            list_alt
            %p あなたの投稿一覧

      %li.global-nav__item
        %a{href: edit_user_registration_path}
          %i.material-icons#material-icons-custom
            settings
            %p 各種設定

      %li.global-nav__item
        %a{href: destroy_user_session_path,  method: :delete}
          %i.material-icons#material-icons-custom
            exit_to_app
            %p ログアウト


=render 'shared/footer-bar'

app/views/users/user_topics.haml
.mobile-body
  =render 'shared/header'
  .mobile-body-fixe-flame
    .mobile-body__inner
      - if @no_topics
        .no_message
          #{@no_topics}
      =render partial: 'user-topics', collection: @topic, as: :topic
  -# =render 'shared/footer'