config/routes.rb
Rails.application.routes.draw do

  resources :soudan, only: [:index, :kiyaku, :privacy_policy]
  root 'soudan#index'

  devise_for :users, controllers: {
  omniauth_callbacks: 'users/omniauth_callbacks',
  confirmations: 'users/confirmations',
  passwords:     'users/passwords',
  registrations: 'users/registrations',
  sessions:      'users/sessions',
  }

  devise_scope :user do
    get '/users/sign_out' => 'users/sessions#destroy'
  end

  resources :users do
    resources :bads, only: [:create, :destroy]
    resources :user_chat_rooms, only: [:index], as: 'chat_rooms'
    resources :messages, only: [:create, :destroy]
    resources :messages do
      resources :thanks, only: [:create, :destroy]
      resources :bads, only: [:create, :destroy]
    end
  end

  resources :users, path: '/', only: [:user_topics]


  resources :topics do
    resource :closes, only: [:create]
    resources :chat_rooms
  end

  get 'test', to: 'soudan#test', as: 'test'
  get 'user/index', to: 'users#index', as: 'user_index'
  get 'users/:id/topics', to: 'users#user_topics', as: 'user_topics'
  get 'search', to: 'topics#search', as: 'topics_search'
  get 'category', to: 'topics#category', as: 'category_search'
  get 'kiyaku', to: 'soudan#kiyaku', as: 'kiyaku'
  get 'privacy_policy', to: 'soudan#privacy_policy', as: 'privacy_policy'
  get 'contact', to: 'soudan#contact', as: 'contact'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bad.rb
class Bad < ApplicationRecord

  belongs_to :message
  belongs_to :user
end

app/models/block.rb
class Block < ApplicationRecord

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :topic
  mount_uploader :image, ImageUploader
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  include IdGenerator

  has_many :users, through: :user_chat_room
  has_many :user_chat_rooms
  belongs_to :topic
  has_many :messages


end

app/models/close.rb
class Close < ApplicationRecord

  has_one :topic
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image_path, ImageUploader

end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :user

end

app/models/message.rb
class Message < ApplicationRecord
  include IdGenerator

  belongs_to :chat_room
  belongs_to :user
  has_one :thank
  has_one :bad

  validates :content, presence: true

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
end

app/models/thank.rb
class Thank < ApplicationRecord

  belongs_to :message
  belongs_to :user
end

app/models/topic.rb
class Topic < ApplicationRecord
  include IdGenerator

  belongs_to :category
  belongs_to :user
  has_many :chat_rooms, dependent: :destroy
  has_one :close

  validates :title, presence: true
  validates :text, presence: true
  validates :category_id, presence: true


end

app/models/user.rb
class User < ApplicationRecord
  include IdGenerator

  mount_uploader :image, ImageUploader

  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :omniauthable,
         omniauth_providers: %i[line google_oauth2]

  has_many :messages
  has_many :topics
  has_many :chat_rooms, through: :user_chat_room
  has_many :user_chat_rooms
  has_many :thanks, dependent: :destroy
  has_many :bads, dependent: :destroy

end

app/models/user_chat_room.rb
class UserChatRoom < ApplicationRecord
  include IdGenerator

  belongs_to :user
  belongs_to :chat_room
end

app/controllers/bads_controller.rb
class BadsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_variables

  def create
    Bad.create(user_id: params[:user_id], message_id: params[:message_id])
    render 'bad_ajax.js.erb'
  end

  def destroy
    bad = Bad.find(params[:id])
    bad.destroy
    render 'bad_ajax.js.erb'
  end

  private
  def set_variables
    @message = Message.find(params[:message_id])
    @id_name = "#bad-btn-#{@message.id}"
  end

end

app/controllers/closes_controller.rb
class ClosesController < ApplicationController
  before_action :authenticate_user!

  def create
    @close = Close.create(topic_id: params[:topic_id])
    redirect_to user_topics_path(id: current_user.id)
  end


end

app/controllers/soudan_controller.rb
class SoudanController < ApplicationController
  before_action :set_user, only: [:index]

  def test
  end


  private
    def set_user
      if user_signed_in?
        @user = User.find(current_user.id)
      else
        root_path
      end
    end
end

app/controllers/thanks_controller.rb
class ThanksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_variables

  def create
    Thank.create(user_id: params[:user_id], message_id: params[:message_id])
    render 'thank_ajax.js.erb'
  end

  def destroy
    thank = Thank.find(params[:id])
    thank.destroy
    render 'thank_ajax.js.erb'
  end

  private
  def set_variables
    @message = Message.find(params[:message_id])
    @id_name = "#thanks-btn-#{@message.id}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :edit, :update, :destroy, :user_topics, :mypage]
  before_action :set_user, only: [:show, :update, :destroy, :user_topics, :mypage]

  def index
    @user = User.new
    @users = User.all
  end



  def show
        @user = User.find(params[:id])
  end

  def user_topics
    if Topic.where(user_id: current_user.id).present?
      @topic = Topic.where(user_id: current_user.id).order(updated_at: "DESC")
    else
      @no_topics = "投稿はありません"
    end
  end

  private
    def set_user
      if current_user.id == params[:id]
        @user = User.find(params[:id])
      else
        redirect_to new_user_session_path
      end
    end



end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end

  def resource
      @resource ||= User.new
  end

  def devise_mapping
      @devise_mapping ||= Devise.mappings[:user]
  end

  def header_title
    case params.values_at :controller, :action
    when ['user_chat_rooms', 'index']
      "メッセージ一覧"
    when ['chat_rooms', 'show']
      "メッセージルーム"
    when ['topics', 'index']
      "投稿一覧"
    when ['topics', 'new']
      "相談"
    when ['users/registrations', 'new']
      "新規登録"
    when ['users/sessions', 'index']
      "ログイン"
    when ['users', 'user_topics']
      "ユーザー投稿一覧"
    when ['soudan', 'kiyaku']
      "利用規約"
    when ['soudan', 'privacy_policy']
      "プライバシーポリシー"
    else

    end
  end

# 　未読メッセージ表示のメソッド
  def new_message_badge
    receive_user = Message.where(receive_user_id: current_user.id).count
    receive_user_checked_message = Message.where(receive_user_id_checked_message: current_user.id).count
    message_count = receive_user - receive_user_checked_message
    if 0 == message_count
    else
      # 未読メッセージがある際にdiv要素を吐き出させてハンバーガーメニュー内に配置する。
      # 未読メッセージが無い際に未読バッジを表示させないため
      content_tag(:div, message_count, class: 'new-message-badge')
    end
  end


  # デバイスのエラーメッセージ出力メソッド
  def devise_error_messages
    return "" if resource.errors.empty?
    html = ""
    # エラーメッセージ用のHTMLを生成
    messages = resource.errors.full_messages.each do |msg|
      html += <<-EOF
        <div class="devise_error_messages" role="alert">
          <p class="error_msg">・#{msg}</p>
        </div>
      EOF
    end
    html.html_safe
  end

end

app/views/rooms/show.html.haml
.breadcrumbs-header-contener
  .breadcrumbs-header
    - breadcrumb :message_room
    = breadcrumbs separator: " &nbsp;&nbsp;&#12297;&nbsp; "



.main-body
  .message-page
    = render "shared/side-bar"
    .message-page-right
      .message-container
        .message-container__inner-left
          .message-container__user-avater
            = image_tag current_user.avater
        .message-container__inner-right
          .message-container__input-message
            = form_for @message do |f|
              = f.text_area :content, placeholder: "メッセージを入力して下さい" , class: "message-input-area", "turbolinks": false, autocomplete: "off"
              = f.hidden_field :room_id, value: @room.id
              = f.submit "送信", class: "message-btn"
      - @messages.each do |m|
        .message-container__message-box
          .message-box__left
            .message-box__avater
              = image_tag m.user.avater
          .message-box__right
            .message-box__info
              .message-box__send-user-name
                %strong
                  = m.user.name
              .message-box__send-time
                %p 送信日：
                = l(m.created_at, format: :long)
            .message
              = simple_format(m.content)
-# %h1 DM
-# %h4 参加者
-# - @entries.each do |e|
-#   %h5
-#     %strong
-#       %a{:href => "/users/#{e.user.id}"}
-#         = e.user.name
-#         さん
-# %hr/
-# - if @messages.present?
-#   - @messages.each do |m|
-#     %strong= m.content
-#     %small
-#       by
-#       %strong
-#         %a{:href => "/users/#{m.user_id}"}
-#           = m.user.name
-#           さん
-#     %hr/
-# - else
-#   %h3.text-center メッセージはまだありません
-# = form_for @message do |f|
-#   = f.text_area :content, placeholder: "メッセージを入力して下さい" , size: 70
-#   = f.hidden_field :room_id, value: @room.id
-#   %br/
-#   = f.submit "投稿する"
-# = link_to "ユーザー一覧に戻る", users_path









-# %h1 DM
-# %h4 参加者
-# - @entries.each do |e|
-#   %h5
-#     %strong
-#       %a{:href => "/users/#{e.user.id}"}
-#         = e.user.name
-#         さん
-# %hr/
-# - if @messages.present?
-#   - @messages.each do |m|
-#     %strong= m.content
-#     %small
-#       by
-#       %strong
-#         %a{:href => "/users/#{m.user_id}"}
-#           = m.user.name
-#           さん
-#     %hr/
-# - else
-#   %h3.text-center メッセージはまだありません
-# = form_for @message do |f|
-#   = f.text_area :content, placeholder: "メッセージを入力して下さい" , size: 70
-#   = f.hidden_field :room_id, value: @room.id
-#   %br/
-#   = f.submit "投稿する"
-# = link_to "ユーザー一覧に戻る", users_path

app/views/shared/_breadcrumbs.haml
- case params.values_at :controller, :action

- when ['topics', 'index']
  - breadcrumb :topics_index

- when ['topics', 'new']
  - breadcrumb :topics_new

- when ['topics', 'show']
  - breadcrumb :topics_show

- when ['topics', 'search']
  - breadcrumb :topics_search

- when ['user_chat_rooms', 'index']
  - breadcrumb :user_chat_rooms_index

- when ['chat_rooms', 'index']
  - breadcrumb :users_topic_chat_rooms

- when ['chat_rooms', 'show']
  - breadcrumb :chat_rooms_show

- when ['users', 'show']
  - breadcrumb :user_show

- when ['users/registrations', 'edit']
  - breadcrumb :user_edit

- when ['users/registrations', 'new']
  - breadcrumb :user_signup

- when ['users/sessions', 'new']
  - breadcrumb :user_login

- when ['users', 'user_topics']
  - breadcrumb :user_topics


= breadcrumbs separator: " &nbsp;&nbsp;&#12297;&nbsp; "

app/views/shared/_footer-bar.haml
.footer-bar
  %small
  ©soudan INC. All rights reserved.

app/views/shared/_footer-menubar.haml
.mobile-body__bottom-parts
  - if params[:controller] == 'chat_rooms' && params[:action] == 'room'
    =render 'shared/input-message'

  .mobile-body__footer
    .mobile-body__footer__inner
      .mobile-body__footer__inner__icon-box
        %i.material-icons.md-dark.md-inactive.soudan
          %a{href: new_topic_path} border_color
        %span.icon-item-title 相談する
      .mobile-body__footer__inner__icon-box
        %i.material-icons.md-dark.md-inactive
          %a{href: topics_search_path} search
        %span.icon-item-title カテゴリー
      .mobile-body__footer__inner__icon-box
        %i.material-icons.md-dark.md-inactive
          %a{href: topics_path} format_list_bulleted
        %span.icon-item-title 一覧
      .mobile-body__footer__inner__icon-box
        %i.material-icons.md-dark.md-inactive
          %a{href: user_chat_rooms_path(user_id: current_user.id)}mail
        %span.icon-item-title メッセージ
      .mobile-body__footer__inner__icon-box
        %i.material-icons.md-dark.md-inactive
          %a{href: user_path(current_user.id)} perm_identity
        %span.icon-item-title メニュー

app/views/shared/_footer.haml
.mobile-body__bottom-parts
  - if params[:controller] == 'chat_rooms' && params[:action] == 'room'
    =render 'shared/input-message'

  .mobile-body__footer
    .mobile-body__footer__inner
      .mobile-body__footer__inner__icon-box
        %i.material-icons.md-dark.md-inactive.soudan
          %a{href: new_topic_path} border_color
        %span.icon-item-title 相談する
      .mobile-body__footer__inner__icon-box
        %i.material-icons.md-dark.md-inactive
          %a{href: topics_search_path} search
        %span.icon-item-title カテゴリー
      .mobile-body__footer__inner__icon-box
        %i.material-icons.md-dark.md-inactive
          %a{href: topics_path} format_list_bulleted
        %span.icon-item-title 一覧
      .mobile-body__footer__inner__icon-box
        %i.material-icons.md-dark.md-inactive
          %a{href: user_chat_rooms_path(user_id: current_user.id)}mail
        %span.icon-item-title メッセージ
      .mobile-body__footer__inner__icon-box
        %i.material-icons.md-dark.md-inactive
          %a{href: user_mypage_path(current_user.id)} perm_identity
        %span.icon-item-title メニュー

app/views/shared/_hamburger.haml
%nav.global-nav
  %ul.global-nav__list
    %li.user-infomation
      .my-card
        .my-card__user-avater
          .my-card__user-avater__inner
            = image_tag @user.image
        .my-card__name-and-status
          .my-card__user-name
            %p #{@user.name}
          .my-card__status
            良い評価　
            %p #{@user.thanks.count}
          .my-card__status
            悪い評価　
            %p #{@user.bads.count}


    %li.global-nav__item
      %a{href: topics_search_path}
        %i.material-icons.md-dark.md-inactive#material-icons-custom
          search
          %p カテゴリー検索

    %li.global-nav__item
      %a{href: topics_path}
        %i.material-icons.md-dark.md-inactive#material-icons-custom
          format_list_bulleted
          %p 投稿一覧

    %li.global-nav__item
      %a{href: user_chat_rooms_path(user_id: current_user.id)}
        %i.material-icons.md-dark.md-inactive#material-icons-custom
          message
          %p 送受信メッセージ一覧
      -# 未読メッセージ表示のメソッド（ヘルパーメソッド内参照）
      %p= new_message_badge

    %li.global-nav__item
      %a{href: user_topics_path(current_user.id)}
        %i.material-icons.md-dark.md-inactive#material-icons-custom
          list_alt
          %p あなたの投稿一覧

    %li.global-nav__item
      %a{href: edit_user_registration_path}
        %i.material-icons#material-icons-custom
          settings
          %p 各種設定

    %li.global-nav__item
      %a{href: destroy_user_session_path,  method: :delete}
        %i.material-icons#material-icons-custom
          exit_to_app
          %p ログアウト

    %li#soudan-btn
      %a{href: new_topic_path}
        %i.material-icons.md-dark.md-inactive#material-icons-custom-soudan
          border_color
          %p 相談する

#js-hamburger.hamburger
  %span.hamburger__line.hamburger__line--1
  %span.hamburger__line.hamburger__line--2
  %span.hamburger__line.hamburger__line--3
#js-black-bg.black-bg




  -# .mobile-body__footer
  -#   .mobile-body__footer__inner
  -#     .mobile-body__footer__inner__icon-box
  -#       %i.material-icons.md-dark.md-inactive.soudan
  -#         %a{href: new_topic_path} border_color
  -#       %span.icon-item-title 相談する
  -#     .mobile-body__footer__inner__icon-box
  -#       %i.material-icons.md-dark.md-inactive
  -#         %a{href: topics_search_path} search
  -#       %span.icon-item-title カテゴリー
  -#     .mobile-body__footer__inner__icon-box
  -#       %i.material-icons.md-dark.md-inactive
  -#         %a{href: topics_path} format_list_bulleted
  -#       %span.icon-item-title 一覧
  -#     .mobile-body__footer__inner__icon-box
  -#       %i.material-icons.md-dark.md-inactive
  -#         %a{href: user_chat_rooms_path(user_id: current_user.id)}mail
  -#       %span.icon-item-title メッセージ
  -#     .mobile-body__footer__inner__icon-box
  -#       %i.material-icons.md-dark.md-inactive
  -#         %a{href: user_mypage_path(current_user.id)} perm_identity
  -#       %span.icon-item-title メニュー

app/views/shared/_header-noberger.haml
.mobile-body__headparts
  - flash.each do |key, value|
    = content_tag(:div, value, class: "#{key}", id: "#{key}")
  .mobile-body__header
    .mobile-body__header__service__name
      %a{href: root_path}
        %h5 soudan
    .mobile-body__header__title
      = header_title
    .login-black-btn
      %a{href: new_user_session_path}ログイン

app/views/shared/_header.haml
.mobile-body__headparts
  - flash.each do |key, value|
    = content_tag(:div, value, class: "#{key}", id: "#{key}")

  .mobile-body__header
    .mobile-body__header__service__name
      %a{href: root_path}
        %h5 soudan
    .mobile-body__header__title
      = header_title
    .top-page__search-icon.black-color
      %i.material-icons.md-dark.md-inactive
        %a{href: topics_search_path} search
    - unless user_signed_in?
      - unless params[:controller] == 'users/sessions' && params[:action] == 'new'
        .login-black-btn
          %a{href: new_user_session_path}ログイン
    - else
      =render 'shared/hamburger'
      =render 'shared/toggleNav'
  .bread-crumb
    =render 'shared/breadcrumbs'

app/views/shared/_test.haml
:javascript

app/views/shared/_toggleNav.haml
:javascript
  function toggleNav() {
    var body = document.body;
    var hamburger = document.getElementById('js-hamburger');
    var blackBg = document.getElementById('js-black-bg');

    hamburger.addEventListener('click', function() {
      body.classList.toggle('nav-open');
    });
    blackBg.addEventListener('click', function() {
      body.classList.remove('nav-open');
    });
  }
  toggleNav();

app/views/shared/_togle-signup.haml
/ 切り替えボタンの設定
%button.start-soudan-sm__start-btn#start-soudan__top-page{"data-target" => "#myModal", "data-toggle" => "modal", :type => "button"}
  今すぐ始める
/ モーダルの設定
#myModal.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %h4#exampleModalLabel.modal-title#modal-title アカウント登録
        %button.close{"aria-label" => "閉じる", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×

      .modal-body
        .registration-box#registration-box-modal
          .label-box
            .space-y-sm2
            = form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f|
              = devise_error_messages
              .space-y-sm2
              .label-box__inner
                = f.label "ニックネーム"
                = f.text_field :name, autofocus: true, autocomplete: "off", placeholder: "", class:"input-default"
              .label-box__inner
                = f.label :email
                = f.email_field :email, autofocus: true, autocomplete: "off", placeholder: "例）abc@soudan.com",class:"input-default"
              .label-box__inner
                = f.label :password
                = f.password_field :password, autocomplete: "off", placeholder: "半角英数字６文字以上", class:"input-default"
              .label-box__inner
                = f.label :password_confirmation
                = f.password_field :password_confirmation, autocomplete: "off", class:"input-default"
              .label-box__inner
                = f.submit :アカウント登録, class:"register-btn"
              .sns-select-signin
                -# %p.or SNSで新規登録
                .sns-select-signin__google
                  .sns-select-signin__google_logo
                  %a{href: user_google_oauth2_omniauth_authorize_path} Google
                .sns-select-signin__line
                  .sns-select-signin__line_logo
                  %a{href: user_line_omniauth_authorize_path} LINE
                %small アカウントを作成することにより、利用規約およびプライバシーポリシーに同意されたものとさせていただきます。
      .modal-footer
        =button_to 'ログイン', new_user_session_path,class:"btn btn-danger"
        %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} 閉じる
      / /.modal-footer
    / /.modal-content
  / /.modal-dialog
/ /.modal

app/views/shared/_top-page-header.haml
%section.top-page__headparts
  .top-page__header
    .top-page__logo
    .top-page__title
      %a{href: root_path}
        %h4 soudan
    - unless user_signed_in?
      -# .white-line-btn
      -#   %a{href: new_user_registration_path}ユーザー登録
      .red-btn.top-page
        %a{href: topics_search_path} 今すぐ検索
      .login-wihte-btn
        %a{href: new_user_session_path}ログイン
    - else
      .red-btn
        %a{href: topics_search_path} 今すぐ検索
      =render 'shared/hamburger'
      =render 'shared/toggleNav'